## Image classification with Convolutional Neural Networks

In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# This file contains all the main external libs we'll use
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

/home/xiaoli/anaconda3/envs/pytorch/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
PATH = "data/dogscats/"
sz=224
arch=vgg16
bs=64

In [4]:
# Uncomment the below if you need to reset your precomputed activations
# !rm -rf {PATH}tmp

In [5]:
data = ImageClassifierData.from_paths(PATH, bs=bs, tfms=tfms_from_model(arch, sz))

In [6]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

Downloading: "https://download.pytorch.org/models/vgg16_bn-6c64b313.pth" to /home/xiaoli/.torch/models/vgg16_bn-6c64b313.pth
100%|██████████| 553507836/553507836 [01:53<00:00, 4866980.05it/s]


100%|██████████| 32/32 [00:07<00:00,  4.33it/s]


In [ ]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

100%|██████████| 32/32 [00:12<00:00,  2.64it/s]


In [7]:
learn.fit(0.01, 3, cycle_len=1)

epoch      trn_loss   val_loss   accuracy                      
    0      0.06332    0.031458   0.9885    
    1      0.048833   0.028774   0.989                         
    2      0.046901   0.029155   0.9895                        



[array([0.02916]), 0.9895]

In [8]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)

In [9]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs, num_workers=4)
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [10]:
learn.fit(1e-2, 2)

epoch      trn_loss   val_loss   accuracy                      
    0      0.052348   0.028169   0.991     
    1      0.051785   0.025796   0.9905                        



[array([0.0258]), 0.9905]

In [ ]:
learn.fit(1e-2, 2)

A Jupyter Widget

[ 0.       0.05622  0.0268   0.98926]                         
[ 1.       0.04222  0.02508  0.99072]                          



In [11]:
learn.precompute=False

In [ ]:
learn.precompute?

In [12]:
learn.fit(1e-2, 1, cycle_len=1)

epoch      trn_loss   val_loss   accuracy                     
    0      0.051172   0.024554   0.9905    



[array([0.02455]), 0.9905]

In [ ]:
learn.fit(1e-2, 1, cycle_len=1)

A Jupyter Widget

[ 0.       0.05511  0.02654  0.98909]                         



In [13]:
learn.unfreeze()

In [14]:
lr=np.array([1e-4,1e-3,1e-2])

In [15]:
learn.fit(lr, 1, cycle_len=1)

epoch      trn_loss   val_loss   accuracy                     
    0      0.062926   0.024867   0.99      



[array([0.02487]), 0.99]

In [16]:
learn.fit(lr, 3, cycle_len=1, cycle_mult=2)

epoch      trn_loss   val_loss   accuracy                     
    0      0.042568   0.021816   0.991     
    1      0.03919    0.020403   0.9915                       
    2      0.037772   0.019381   0.9925                       
    3      0.035638   0.020357   0.9915                       
    4      0.028773   0.017747   0.993                        
    5      0.025711   0.018118   0.993                        
    6      0.022463   0.016932   0.993                        



[array([0.01693]), 0.993]

In [ ]:
learn.fit(lr, 3, cycle_len=1, cycle_mult=2)

A Jupyter Widget

[ 0.       0.05955  0.02217  0.9917 ]                         
[ 1.       0.03902  0.0181   0.99414]                         
[ 2.       0.03676  0.0168   0.99414]                         
[ 3.       0.03097  0.01607  0.99316]                         
[ 4.       0.02823  0.01574  0.99316]                         
[ 5.       0.02663  0.01448  0.99316]                         
[ 6.       0.03113  0.01642  0.99414]                         



In [ ]:
learn.fit(lr, 3, cycle_len=3)

A Jupyter Widget

[ 0.       0.02769  0.01896  0.99268]                         
[ 1.       0.01939  0.01417  0.99365]                         
[ 2.       0.01935  0.0142   0.99414]                         
[ 3.       0.02465  0.01641  0.99316]                         
[ 4.       0.02753  0.01376  0.99365]                         
[ 5.       0.01721  0.01413  0.99414]                         
[ 6.       0.0221   0.01317  0.99365]                         
[ 7.       0.01789  0.01379  0.99268]                         
[ 8.       0.01861  0.0139   0.99316]                         



In [ ]:
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)
accuracy_np(probs,y)

0.995

In [18]:
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)
accuracy_np(probs,y)

0.9935